version: '3'

services:
  web-app:
    build: ./web-app
    ports:
      - "8091:8091"
    depends_on:
      - service-app

  service-app:
    build: ./service-app
    ports:
      - "8111:8111"
    depends_on:
      - data-base-app

  data-base-app:
    build: ./data-base-app
    ports:
      - "8101:8101"