version: '3'

services:
  web-app:
    build: ./web-app
    ports:
      - "8091:8091"
    depends_on:
      - service-app

  service-app:
    build: ./service-app
    ports:
      - "8111:8111"
    depends_on:
      - data-base-app

  data-base-app:
    build: ./data-base-app
    ports:
      - "8101:8101"

  database:
    image: postgres:15
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  liquibase:
    image: liquibase/liquibase:latest
    environment:
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://database:5432/mydatabase
      LIQUIBASE_COMMAND_USERNAME: myuser
      LIQUIBASE_COMMAND_PASSWORD: mypassword
      LIQUIBASE_COMMAND_CHANGELOG_FILE: db.changelog.xml
      LIQUIBASE_SEARCH_PATH: /liquibase/changelog
    volumes:
      - ./liquibase/changelog:/liquibase/changelog
    depends_on:
      - database
    entrypoint: [ "liquibase", "--changeLogFile=db.changelog.xml", "update" ]